model_reasoning_effort = "high"
hide_agent_reasoning = false
tools_web_search_request = true

[assistant]
language = "ja"

[mcp]
servers = [
  { name = "microsoft.docs.mcp", type = "http", url = "https://learn.microsoft.com/api/mcp" }
]
