extra:
  author: komiyamma
  author_alternate: こみやんま
  author_sameas:
    - https://x.com/komiyamma
    - https://github.com/komiyamma
  default_image: assets/images/default_ogp.png
  site_title_primary: Techニュース
  site_title_separator: ｜
  parent_site:
    name: komiyamma.net
    url: https://komiyamma.net/
site_name: Techニュース｜komiyamma.net
site_description: Techに関するニュースをまとめています。
site_url: https://tech-news.komiyamma.net
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.indexes
plugins:
  - search:
      lang:
        - ja
        - en
  - macros:
      include_dir: macros
      modules:
        - macros.home
      verbose: false
  - title_from_filename
  - description_from_memo
  - exclude_docs:
      patterns:
        - AGENTS.md
        - my_command.md
        - gemini_command.md
        - gemini.md
  - awesome-pages
hooks:
  - hooks.py
extra_css:
  - stylesheets/extra.css
